# permissions for end users to view builddeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builddeploy-viewer-role
rules:
- apiGroups:
  - cicd.innkeeper.run
  resources:
  - builddeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cicd.innkeeper.run
  resources:
  - builddeploys/status
  verbs:
  - get
